accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'

urlpatterns = [
    path('login/', login_check, name='login'),
    # path('logout/', auth_views.logoutas_view(), name='logout', kwargs={'next_page': 'login'}),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('password_change/', password_change, name='password_change'),
    path('account_change/', account_change, name='account_change'),
    path('follow/', follow, name='follow'),



    # url(r'^login/$', views.login, name='login'),
    # url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'accounts/login.html'}),

    # url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': 'login'}),
    # url(r'^signup/$', views.signup, name='signup'),
    # url(r'^password_change/$', views.password_change, name='password_change'),
    # url(r'^account_change/$', views.account_change, name='account_change'),
    # url(r'^follow/$', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root'),
]

# NOTE: serving media files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# NOTE: debug_toolbar용 url 설정
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('<username>/list', my_post_list, name='my_post_list'),
    path('<username>/list/detail', my_post_list_detail, name='my_post_list_detail'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('follow', follow_post_list, name='follow_post_list'),
    path('like', post_like, name='post_like'),
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('comment/more', comment_more, name='comment_more'),
    path('explore/tags/<tag>/', post_list, name='post_search'),

    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^new/$', views.post_new, name='post_new'),



    # url(r'^explore/tags/(?P<tag>\w+)/$', views.post_list, name='post_search'),

    # url(r'^(?P<username>\w+)/list/$', views.my_post_list, name='my_post_list'),
    # url(r'^(?P<username>\w+)/list/detail/$', views.my_post_list_detail, name='my_post_list_detail'),
    # url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    # url(r'^comment/new/$', views.comment_new, name='comment_new'),
    # url(r'^comment/delete/$', views.comment_delete, name='comment_delete'),
    # url(r'^comment/more/$', views.comment_more, name='comment_more'),
    # url(r'^like/$', views.post_like, name='post_like'),
    # url(r'^follow/$', views.follow_post_list, name='follow_post_list'),
    # url(r'^(?P<username>\w+)/list/follow/$', views.follow_list, name='follow__list'),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return 'accounts/{}/{}.{}'.format(instance.user.username, pid, extension)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField('닉네임', max_length=30, unique=True)
    follow_set = models.ManyToManyField('self',
                                        blank=True,
                                        through='Relation',
                                        symmetrical=False, )
    picture = ProcessedImageField(upload_to=user_path,
                                  processors=[ResizeToFill(150, 150)],
                                  format='JPEG',
                                  options={'quality': 90},
                                  blank=True,
                                  )
    about = models.CharField(max_length=150, blank=True)
    GENDER_CHOICES = (
        ('선택 안 함', '선택 안 함'),
        ('여성', '여성'),
        ('남성', '남성'),
    )
    gender = models.CharField('성별(선택사항)', max_length=10, choices=GENDER_CHOICES, default='N')

    def __str__(self):
        return self.nickname

    @property
    def get_follower(self):
        return [i.from_user for i in self.follower_user.all()]

    @property
    def get_following(self):
        return [i.to_user for i in self.follow_user.all()]

    @property
    def follower_count(self):
        return len(self.get_follower)

    @property
    def following_count(self):
        return len(self.get_following)

    def is_follower(self, user):
        return user in self.get_follower

    def is_following(self, user):
        return user in self.get_following


class Relation(models.Model):
    from_user = models.ForeignKey(Profile, related_name='follow_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(Profile, related_name='follower_user', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} -> {}".format(self.from_user, self.to_user)

    class Meta:
        unique_together = (
            ('from_user', 'to_user')
        )

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Profile
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]


class SignupForm(UserCreationForm):
    username = forms.CharField(label='사용자명', widget=forms.TextInput(attrs={
        'pattern': '[a-zA-Z0-9]+',
        'title': '특수문자, 공백 입력불가',
    }))

    nickname = forms.CharField(label='닉네임')
    picture = forms.ImageField(label='프로필 사진', required=False)

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)  # NOTE: User 모델의 email field 사용

    # NOTE: clean_<필드명> 메서드를 활용하여, is_valid() 메소드 실행시 nickname 필드에 대한 유효성 검증 실행
    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if Profile.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError('이미 존재하는 닉네임 입니다.')
        return nickname

    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('사용중인 이메일 입니다.')  # NOTE: 유효성 검사 에러메시지 생성
        return email

    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            picture = None
        return picture

    def save(self):
        user = super().save()
        Profile.objects.create(
            user=user,
            nickname=self.cleaned_data['nickname'],
            picture=self.cleaned_data['picture'], )
        return user


class ProfileForm(forms.ModelForm):
    about = forms.CharField(label='자기소개', required=False, widget=forms.Textarea(attrs={
        'rows': 4,
        'cols': 50,
        'placeholder': '소개는 150자 까지 등록 가능합니다', }))

    class Meta:
        model = Profile
        fields = ['nickname', 'picture', 'about', 'gender']
        labels = {
            'picture': '프로필 사진',
        }

    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            picture = None
        return picture

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        # self.fields['nickname'].label = '닉네임'
        # self.fields['picture'].label = '프로필 사진'
        # self.fields['about'].label = '자기소개'
        # self.fields['gender'].label = '성별(선택사항)'
        # https://github.com/django/django/blob/1.10.6/django/forms/models.py#L185

accounts/views.py
import json
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
# from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from django.contrib.auth import logout as django_logout
# from django.contrib.auth.views import LoginView
#
#
# from allauth.socialaccount.models import SocialApp
# from allauth.socialaccount.templatetags.socialaccount import get_providers
from .forms import SignupForm, ProfileForm, LoginForm
from .models import Profile, Relation



def login_check(request):
    if request.method == "POST":
        #사용자가 로그인 폼에 입력한 값
        form = LoginForm(request.POST)
        name = request.POST["username"]
        pwd = request.POST["password"]
        #인증
        user = authenticate(username=name, password=pwd)
        if user is not None: # 로그인 성공
            login(request, user)
            return redirect("/")
        else: #로그인 실패
            return render(request, "accounts/login.html", {"msg": "아이디 패스워드를 확인해 주세요 ^ ^"})
    else: #get 방식인 경우 - 로그인 페이지로 이동
        form = LoginForm()
        return render(request, 'accounts/login.html', {"form":form})


    # if request.method == 'POST':
    #     # 로그인 성공 후 이동할 URL. 주어지지 않으면 None
    #     next = request.GET.get('next')
    #
    #     # Data bounded form인스턴스 생성
    #     # AuthenticationForm의 첫 번째 인수는 해당 request가 되어야 한다
    #     login_form = LoginForm(request=request, data=request.POST)
    #
    #     # 유효성 검증에 성공할 경우
    #     # AuthenticationForm을 사용하면 authenticate과정까지 완료되어야 유효성 검증을 통과한다
    #     if login_form.is_valid():
    #         # AuthenticatonForm에서 인증(authenticate)에 성공한 유저를 가져오려면 이 메서드를 사용한다
    #         user = login_form.get_user()
    #         # Django의 auth앱에서 제공하는 login함수를 실행해 앞으로의 요청/응답에 세션을 유지한다
    #         django_login(request, user)
    #         # next가 존재하면 해당 위치로, 없으면 Post목록 화면으로 이동
    #         return redirect(next if next else 'post:post_list')
    #     # 인증에 실패하면 login_form에 non_field_error를 추가한다
    #     login_form.add_error(None, '아이디 또는 비밀번호가 올바르지 않습니다')
    # else:
    #     login_form = LoginForm()
    #
    # context = {
    #     'login_form': login_form,
    # }
    #
    #
    # providers = []
    # for provider in get_providers():  # settings/INSTALLED_APPS 내에서 활성화된 목록
    #     # social_app속성은 provider에는 없는 속성입니다.
    #     try:
    #         # 실제 provider 별 Client id/secret 이 등록이 되어 있는가?
    #         provider.social_app = SocialApp.objects.get(provider=provider.id, sites=settings.SITE_ID)
    #     except SocialApp.DoesNotExist:
    #         provider.social_app = None
    #     providers.append(provider)
    # return render(request, 'accounts/login.html', {'providers': providers}, context)


def logout(request):
    django_logout(request)
    return redirect("/")


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():  # clean_<필드명> 메소드 호출
            user = form.save()
            return redirect('accounts:login')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, '비밀번호가 정상적으로 변경되었습니다.')
            return redirect('post:my_post_list', request.user.username)
        else:
            messages.error(request, '오류가 발생하였습니다.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password_change.html', {
        'form': form,
    })


@login_required
def account_change(request):
    profile = get_object_or_404(Profile, pk=request.user.profile.id)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save()
            messages.success(request, '회원정보가 정상적으로 변경되었습니다.')
            return redirect('post:my_post_list', request.user.username)
        else:
            messages.error(request, '오류가 발생하였습니다.')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'accounts/account_change.html', {
        'form': form,
    })


@login_required
@require_POST
def follow(request):
    from_user = request.user.profile
    pk = request.POST.get('pk')
    to_user = get_object_or_404(Profile, pk=pk)
    relation, created = Relation.objects.get_or_create(from_user=from_user, to_user=to_user)

    if created:
        message = '팔로우 시작!'
        status = 1
    else:
        relation.delete()
        message = '팔로우 취소'
        status = 0

    context = {
        'message': message,
        'status': status,
    }
    return HttpResponse(json.dumps(context), content_type="application/json")

accounts/templates/accounts/account_change.html
{% extends "accounts/layout.html" %}
{% load static %}
{% block title %} 회원정보 변경 {% endblock %}
{% block content %}
<div class="form-container account-form-container">
  <form class="form account-form" action="" method="post" enctype="multipart/form-data">
    <div class="user-title">
      {% if user.profile.picture %}
      <img class="account-pic" src="{{ user.profile.picture.url }}" alt="프로필사진">
      {% else %}
      <img class="account-pic" src="{% static 'images/default/default.jpg' %}" alt="프로필사진">
      {% endif %}
      <h1 class="usernsme">{{ user.username }} 프로필 편집</h1>
    </div>
    {% csrf_token %}
    {{ form.as_p}}
    <input class="submit_btn" type="submit">
  </form>
  <div class="shortcut">
    <p class="signup-link">비밀번호 변경을 원하시나요? <a href="{% url "accounts:password_change" %}">비밀번호 변경</a></p>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}
{% load socialaccount %}

{% block title %}
로그인 | Instagram
{% endblock %}

{% block content %}
<div class="form-container">
  <div class="form">
    <h1 class="title">Instagram</h1>
      {% if msg %}
      <p>
        {{ msg }}
      </p>
      {% endif %}
    <form method="POST" action="{% url 'accounts:login' %}">

      {% csrf_token %}


      <p>
        <label for="id_username">사용자명:</label>
        <input id="{{ form.username.id_for_label }}" maxlength="15" name="{{ form.username.html_name }}">
      </p>
      <p>
        <label for="id_username">비밀번호:</label>
        <input id="{{ form.password.id_for_label }}" maxlength="120" name="{{ form.password.html_name }}" type="password">
      </p>

      <input class="submit_btn" type="submit" value="로그인">
      {% for provider in providers %}
      {% if provider.social_app %}
      <a href="{% provider_login_url provider.id %}"><p class="submit_btn social_login_btn"><span class=""></span>{{ provider.name }}으로 로그인</p></a>
      {% else %}
      Provider {{ provider.name }} 설정이 필요합니다.
      {% endif %}
      {% endfor %}
    </form>
  </div>
  <div class="shortcut">
    <p class="signup-link test-account">테스트 사용자명 : test / 비밀번호 : test2019</p>
    <p class="signup-link">아이디가 없으신가요? <a href="{% url "accounts:signup" %}">회원가입</a></p>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/layout.html" %}
{% load socialaccount %}

{% block title %}
로그아웃 | Instagram
{% endblock %}

{% block content %}
<div class="form-container">
  <div class="form">
    <h1 class="title">Instagram</h1>
    <form action="" method="post">
      {% csrf_token %}
        {{ form.as_p }}
      <input class="submit_btn" type="submit" value="로그인">

    </form>
  </div>
  <div class="shortcut">
    <p class="signup-link test-account">테스트 사용자명 : test / 비밀번호 : test2017</p>
    <p class="signup-link">아이디가 없으신가요? <a href="{% url "signup" %}">회원가입</a></p>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "accounts/layout.html" %}
{% block title %} 비밀번호 변경 {% endblock %}
{% block content %}
<div class="form-container account-form-container">
<form class="form account-form" action="" method="post" enctype="multipart/form-data">
  <div class="user-title">
    <h1 class="form-title">비밀번호 수정</h1>
  </div>
  {% csrf_token %}
  {{ form.as_p }}
  <input class="submit_btn" type="submit">
</form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block title %}
프로필 | Instagram
{% endblock %}

{% block content %}

<h3>{{ user.profile.nickname }}'s 프로필</h3>
<ul>
  {% if user.profile.picture %}
  <li>picture:<img src="{{ user.profile.picture.url }}" alt=""></li>
  {% endif %}
  <li>username : {{ user.username }}</li>
  <li>email : {{ user.email }}</li>
  <li>nickname : {{ user.profile.nickname }}</li>
  <li>소개: {{ user.profile.about }}</li>
  <li>성별: {{ user.profile.gender }}</li>
  <li><a href="{% url "logout" %}">로그아웃</a></li>
  <li><a href="{% url "account_change" %}">회원정보 변경</a></li>
  <li><a href="{% url "password_change" %}">비밀번호 변경</a></li>
</ul>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block title %}
회원가입 | Instagram
{% endblock %}

{% block content %}
<div class="form-container">
  <div class="form">
    <h1 class="title">Instagram</h1>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
        {{ form.as_p }}
      <input class="submit_btn" type="submit" value="가입">
    </form>
  </div>
  <div class="shortcut">
  <p class="link">계정이 있으신가요? <a href="{% url "accounts:login" %}">로그인</a></p>
  </div>
</div>
{% endblock %}