accounts/urls.py
from django.urls import path
from .views import *


app_name = 'accounts'

urlpatterns = [
    path('login/', login_check, name='login'),
    # path('logout/', auth_views.logoutas_view(), name='logout', kwargs={'next_page': 'login'}),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('password_change/', password_change, name='password_change'),
    path('account_change/', account_change, name='account_change'),
    path('follow/', follow, name='follow'),



    # url(r'^login/$', views.login, name='login'),
    # url(r'^login/$', auth_views.login, name='login', kwargs={'template_name': 'accounts/login.html'}),

    # url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': 'login'}),
    # url(r'^signup/$', views.signup, name='signup'),
    # url(r'^password_change/$', views.password_change, name='password_change'),
    # url(r'^account_change/$', views.account_change, name='account_change'),
    # url(r'^follow/$', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root'),
]

# NOTE: serving media files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# NOTE: debug_toolbar용 url 설정
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('<username>/list', my_post_list, name='my_post_list'),
    path('<username>/list/detail', my_post_list_detail, name='my_post_list_detail'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('follow', follow_post_list, name='follow_post_list'),
    path('like', post_like, name='post_like'),
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('comment/more', comment_more, name='comment_more'),
    path('explore/tags/<tag>/', post_list, name='post_search'),

    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^new/$', views.post_new, name='post_new'),



    # url(r'^explore/tags/(?P<tag>\w+)/$', views.post_list, name='post_search'),

    # url(r'^(?P<username>\w+)/list/$', views.my_post_list, name='my_post_list'),
    # url(r'^(?P<username>\w+)/list/detail/$', views.my_post_list_detail, name='my_post_list_detail'),
    # url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    # url(r'^comment/new/$', views.comment_new, name='comment_new'),
    # url(r'^comment/delete/$', views.comment_delete, name='comment_delete'),
    # url(r'^comment/more/$', views.comment_more, name='comment_more'),
    # url(r'^like/$', views.post_like, name='post_like'),
    # url(r'^follow/$', views.follow_post_list, name='follow_post_list'),
    # url(r'^(?P<username>\w+)/list/follow/$', views.follow_list, name='follow__list'),
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re


def photo_path(instance, filename):
    from time import gmtime, strftime
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'), instance.author.username, pid, extension)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path,
                                processors=[ResizeToFill(600, 600)],
                                format='JPEG',
                                options={'quality': 90})
    content = models.CharField(max_length=140, help_text="최대 140자 입력 가능")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField('Tag', blank=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')  # post.like_set 으로 접근 가능

    class Meta:
        ordering = ['-created_at']

    # NOTE: content에서 tags를 추출하여, Tag 객체 가져오기, 신규 태그는 Tag instance 생성, 본인의 tag_set에 등록,
    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)  # NOTE: ManyToManyField 에 인스턴스 추가

    @property
    def like_count(self):
        return self.like_user_set.count()

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.content

post/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='', required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자 까지 등록 가능합니다.\n#태그명 을 통해서 검색 태그를 등록할 수 있습니다. \n예시 : I #love #coding!', }))

    class Meta:
        model = Post
        fields = ['photo', 'content']


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40', }))

    class Meta:
        model = Comment
        fields = ['content']

post/views.py
import json
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from .models import Comment, Post, Like, Tag
from .forms import CommentForm, PostForm


def post_list(request, tag=None):
    tag_all = Tag.objects.annotate(num_post=Count('post')).order_by('-num_post')

    if tag:
        post_list = Post.objects.filter(tag_set__name__iexact=tag) \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')
    else:
        post_list = Post.objects.all() \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user', ) \
            .select_related('author__profile', )

    comment_form = CommentForm()

    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.is_ajax():  # Ajax request 여부 확인
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })

    if request.method == 'POST':
        tag = request.POST.get('tag')
        tag_clean = ''.join(e for e in tag if e.isalnum())  # 특수문자 삭제
        return redirect('post:post_search', tag_clean)

    return render(request, 'post/post_list.html', {
        'tag': tag,
        'posts': posts,
        'comment_form': comment_form,
        'tag_all': tag_all,
    })


def my_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile

    target_user = get_user_model().objects.filter(id=user.id).select_related('profile') \
        .prefetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')

    post_list = user.post_set.all()

    return render(request, 'post/my_post_list.html', {
        'user_profile': user_profile,
        'target_user': target_user,
        'post_list': post_list,
        'username': username,
    })


def my_post_list_detail(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile

    target_user = get_user_model().objects.filter(id=user.id).select_related('profile') \
        .prefetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')

    post_list = Post.objects.filter(author=user) \
        .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                          'author__profile__follower_user', 'author__profile__follower_user__from_user', ) \
        .select_related('author__profile', )

    comment_form = CommentForm()

    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.is_ajax():  # Ajax request 여부 확인
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })

    return render(request, 'post/my_post_list_detail.html', {
        'user_profile': user_profile,
        'username': username,
        'posts': posts,
        'comment_form': comment_form,
        'target_user': target_user,
    })


def follow_list(request, username):
    pass


@login_required
def follow_post_list(request):
    follow_set = request.user.profile.get_following
    post_list = Post.objects.filter(author__profile__in=follow_set) \
        .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                          'author__profile__follower_user', 'author__profile__follower_user__from_user', ) \
        .select_related('author__profile', )

    comment_form = CommentForm()

    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.is_ajax():  # Ajax request 여부 확인
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })

    return render(request, 'post/post_list.html', {
        'follow_set': follow_set,
        'posts': posts,
        'comment_form': comment_form,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('post:post_list')

    else:
        form = PostForm()
    return render(request, 'post/post_new.html', {
        'form': form,
    })


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.tag_set.clear()  # NOTE: ManyToManyField 의 모든 항목 삭제 (해당 인스턴스 내에서만 적용)
            post.tag_save()
            messages.success(request, '수정완료')
            return redirect('post:post_list')

    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form,
    })


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or request.method == 'GET':
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')

    if request.method == 'POST':
        post.delete()
        messages.success(request, '삭제완료')
        return redirect('post:post_list')


@login_required
@require_POST  # 해당 뷰는 POST method 만 받는다.
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"

    context = {'like_count': post.like_count,
               'message': message,
               'nickname': request.user.profile.nickname}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def comment_new(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,
            })
    return redirect("post:post_list")


@login_required
def comment_delete(request):
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1

    else:
        message = '잘못된 접근입니다.'
        status = 0

    return HttpResponse(json.dumps({'message': message, 'status': status, }), content_type="application/json")


def comment_more(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        comments = post.comment_set.all()[4:]
        return render(request, 'post/comment_more_ajax.html', {
            'comments': comments,
        })
    return redirect("post:post_list")

post/templates/post/comment_new_ajax.html
<div id="comment{{ comment.id }}">
  <span class="comment-username">{{ comment.author.profile.nickname }}</span> {{ comment.content }}
  {% if user == comment.author %}
  <input type="button" class="del-comment" value="삭제" name="{{ comment.id }}">
  {% endif %}
</div>

post/templates/post/my_post_list.html
{% extends "post/layout.html" %}

{% block content %}

<div class="container-fluid">
  <div class="mylist-container">
    {% include "post/include_account.html" %}
    <div class="mylist-content">
      <div class="row">
      {% for post in post_list %}
        <div class="pic col-md-4"><a href="{% url 'post:my_post_list_detail' username %}"><img class="pic-src" src="{{ post.photo.url }}" alt="photo"></a></div>
      {% endfor %}
    </div>
    </div>
  </div>
</div>
{% endblock %}

post/templates/post/post_list.html
{% extends "post/layout.html" %}
{% load humanize %}
{% load post_extras %}
{% load static %}

{% block title %}
{% if tag %}
#{{ tag }} - Instagram
{% else %}
Instagram
{% endif %}
{% endblock %}

{% block content %}


{% if follow_set %}
<div class="search-header">
  <h1 class="search-result-title">팔로우 목록</h1>
</div>
{% elif not posts and not tag %}
<div class="search-header">
  <h1 class="search-result-title">팔로우 중인 유저가 없습니다. 팔로우를 시작해보세요!</h1>
</div>
{% endif %}

{% if tag %}
<div class="search-header">
  {% if not posts %}
  <h1 class="search-result-title">#{{tag}}<br>태그 검색 결과가 없습니다.</h1>
    <div class="hot-tag-list">
    <h2 >인기 태그 리스트</h2>
    {% for tag in tag_all|slice:":5" %}
      <a href="/post/explore/tags/{{tag.name}}">#{{ tag.name }}</a>
    {% endfor %}
    </div>
  {% else %}
  <h1 class="search-result-title">#{{tag}} 검색결과</h1>
  <span class="search-result-count">게시물 <span class="count">{{ posts.paginator.count|intcomma }}개 </span></span>
  {% endif %}
</div>
{% endif %}


{% for post in posts %}
<article class="post-wrap">
  <header>
    <a class="user-title" href="{% url "post:my_post_list" post.author.username %}">
    {% if post.author.profile.picture %}
    <img class="user-pic" src="{{ post.author.profile.picture.url }}" alt="프로필사진">
    {% else %}
    <img class="user-pic" src="{% static 'images/default/default.jpg' %}" alt="프로필사진">
    {% endif %}
    <span class="post-username">{{ post.author.profile.nickname  }}</span>
    </a>
    <span class="pull-right">
      {% if user.profile in post.author.profile.get_follower %}
      {# {% if post.author.profile in user_profile.follow_set.all %}#}
      <input class="follow following-btn" type="submit" value="팔로잉" name="{{ post.author.profile.id }}">
      {% else %}
      <input class="follow follow-btn" type="submit" value="팔로우" name="{{ post.author.profile.id }}">
      {% endif %}
    </span>
    {% if post.author == user %}
    <span class=pull-right>
      <a class="post-edit" href="{% url "post:post_edit" post.pk %}">수정</a>
      <form class="post-delete-form" action="{% url "post:post_delete" post.pk %}" method="post">
        {% csrf_token %}
        <input class="post-delete" type="submit" value="삭제" onclick="return confirm('정말 삭제하시겠습니까?')">
      </form>
    </span>
    {% endif %}
  </header>
  <img src="{{ post.photo.url }}" alt="{{ post.author }}'s photo">
  <div class="post-content">
    {% if user in post.like_user_set.all %}
    <input type="button" class="like liked" name="{{ post.id }}">
    {% else %}
    <input type="button" class="like to-like" name="{{ post.id }}">
    {% endif %}
    <input type="button" class="commnet-icon" name="{{ post.id }}">

    <p class="like-count" id="count-{{ post.id }}">좋아요 {{ post.like_count }}개</p>

    <p id="like-user-{{post.id}}">
    {% if post.like_count != 0 %}
      {% if post.like_user_set.all %}
      {% for like_user in post.like_user_set.all %}
      {{ like_user.profile.nickname }}
      {% endfor %}
      님이 좋아합니다.
      {% endif %}
    {% endif %}
    </p>

    <span class="post-username">{{ post.author.profile.nickname }}</span>
    <span>{{ post|add_link|safe|linebreaksbr }}</span>




    {% if post.comment_set.all.count > 4 %}
    <input type="button" class="comment-more" name="{{ post.id }}" value="댓글 더 보기">
    {% endif %}
    <div id="comment-list-ajax-post{{post.id}}"></div>
    {% for comment in post.comment_set.all|slice:":4" %}
    <div id="comment{{ comment.id }}">

      <span class="comment-username">{{ comment.author.profile.nickname }}</span> {{ comment.content }}
      {% if user == comment.author %}
      <input type="button" class="del-comment" value="삭제" name="{{ comment.id }}">
      {% endif %}

    </div>
    {% endfor %}
    <div id="comment-more-{{post.id}}"></div>

    <div class="time">
    {{ post.created_at|naturaltime }}
    </div>
    <div id="add-comment-post{{post.id}}" class="add-comment-wrap">
    {% if user.is_authenticated %}
      {{ comment_form }}
      <input type="button" class="add-comment add-comment-btn" name="{{ post.id }}" value="게시">
    {% else %}
      {{ comment_form }}
      <input type="button" class="add-comment-btn" name="{{ post.id }}" value="게시" onclick="alert('댓글을 작성하려면 로그인이 필요합니다.')">
    {% endif %}
    </div>
  </div>
  </article>
  {% endfor %}

  <div id="post_list_ajax"></div>
  <input id="page" type="hidden" value="2">

  {% if posts.paginator.count > 4 %}
  <button id="callmorepost" type="button">More Post</button>
  {% endif %}

  {% include "post/script_ajax.html" %}
  {% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
///////////////// 팔로우 Ajax /////////////////
 $(document).on('click', '.follow', function(){
  var pk = $(this).attr('name');
  $.ajax({
    type: "POST",
    url: "{% url 'accounts:follow' %}",
    data: {
      'pk': pk,
      'csrfmiddlewaretoken': '{{ csrf_token }}',
    },
    dataType: "json",

    success: function(response){
      alert(response.message);

      if(response.status){
        $("input.follow[name="+pk+"]").val("팔로잉");
        $("input.follow[name="+pk+"]").toggleClass('follow-btn following-btn');
      }else{
        $("input.follow[name="+pk+"]").val("팔로우");
        $("input.follow[name="+pk+"]").toggleClass('following-btn follow-btn');
      }

    },
    error: function(request, status, error){
      alert("로그인이 필요합니다.");
      window.location.replace("/accounts/login/");
      // alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
    }
  })
 });

///////////////// 좋아요 Ajax /////////////////
    $(document).on('click', '.like', function(){
    var pk = $(this).attr('name');
    $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
      type: "POST", // 데이터를 전송하는 방법을 지정
      url: "{% url 'post:post_like' %}", // 통신할 url을 지정
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
      dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단

      // 서버측에서 전송한 Response 데이터 형식 (json)
      // {'likes_count': post.like_count, 'message': message }

      success: function(response){ // 통신 성공시 - 좋아요 갯수 변경, 유저 목록 변경
        alert(response.message);

        $("#count-"+pk).html("좋아요 "+response.like_count+"개");

        var users = $("#like-user-"+pk).text();

        if(users.indexOf(response.nickname) != -1){
          if(response.like_count == 0){
            $("#like-user-"+pk).text("");
          }else{
          $("#like-user-"+pk).text(users.replace(response.nickname, ""));
          }
          $("input.like[name="+pk+"]").toggleClass('liked to-like');
        }else{
          $("#like-user-"+pk).text(response.nickname+users);
          $("input.like[name="+pk+"]").toggleClass('to-like liked');
        }
      },
      error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트
        alert("로그인이 필요합니다.");
        window.location.replace("/accounts/login/");
        //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      },
    });
  });


///////////////// 댓글 작성하기 /////////////////
  $(document).on('click', '.commnet-icon', function(){
    var pk = $(this).attr('name');
    $("#add-comment-post"+pk+">input[type=text]").focus();
  });

///////////////// 댓글등록 Ajax /////////////////

  $(document).on('click', '.add-comment', function(){
    var pk = $(this).attr('name');
    var content = $("#add-comment-post"+pk+">input[type=text]").val();
    if(content.length > 140){
      alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
      return;
    }
    $.ajax({
      type: "POST",
      url: "{% url 'post:comment_new' %}",
      data: {
        'pk': pk,
        'content':content,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
      dataType: "html",

      success: function(data, textStatus, jqXHR){
        alert("댓글을 추가하였습니다.");
        $("#add-comment-post"+pk+">input[type=text]").val("");
        $("#comment-list-ajax-post"+pk).append(data);
      },
      error: function(request, status, error){
        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        alert("문제가 발생했습니다.");
      },
    });
  });


///////////////// 댓글삭제 Ajax /////////////////
  $(document).on('click', '.del-comment', function(){
    var pk = $(this).attr('name');
    $.ajax({
      type: "POST",
      url: "{% url 'post:comment_delete' %}",
      data: {
        'pk': pk,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
      dataType: "json",
      success: function(response){
        if(response.status){
          $('#comment'+pk).remove();
        }
        alert(response.message);
      },
      error: function(request, status, error){
        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        alert("문제가 발생했습니다.");
      },
    });
  });


///////////////// 댓글 더보기 Ajax /////////////////

  $(document).on('click', '.comment-more', function(){
    var pk = $(this).attr('name');

    $.ajax({
      type: "POST",
      url: "{% url 'post:comment_more' %}",
      data: {
        'pk': pk,
        'csrfmiddlewaretoken': '{{ csrf_token }}',
      },
      dataType: "html",

      success: function(data, textStatus, jqXHR){
        $("#comment-more-"+pk).append(data);
        $(".comment-more[name="+pk+"]").remove();
      },

      error: function(request, status, error){
        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        alert("문제가 발생했습니다.");
      },
    });
  });



///////////////// 무한 스크롤 Ajax /////////////////
  $('#callmorepost').click(function(){
    var page = $("#page").val();
    var end_page = {{ posts.paginator.num_pages }};
    if(page > end_page){
      return;
    }
    callMorePostAjax(page);
    $("#page").val(parseInt(page)+1);
  });

  $(window).scroll(function(){
    var scrollHeight = $(window).scrollTop() + $(window).height();
    var documentHeight = $(document).height();

    // console.log("documentHeight:" + documentHeight);
    // console.log("windowHeight:" + $(window).height());
    // console.log("scrollHeight:" + scrollHeight);

    if (scrollHeight  >= documentHeight){
      var page = $("#page").val();
      var end_page = {{ posts.paginator.num_pages }};
      if(page > end_page){
        return;
      }
      callMorePostAjax(page);
      $("#page").val(parseInt(page)+1);
    }
  });

  function callMorePostAjax(page) {
    var end_page = {{ posts.paginator.num_pages }};
    if(page > end_page){
      return;
    }
    $.ajax({
      type : 'POST',
      {% if tag %}
      url: "{% url 'post:post_search' tag %}", // tag 여부에 따라서 분기처리
      {% elif follow_set %}
      url: "{% url 'post:follow_post_list' %}", // view에서 넘겨준 follow_set 여부에 따라서 분기처리
      {% else %}
      url: "{% url 'post:post_list' %}",
      {% endif %}
      data: {
        'page': page,
        'csrfmiddlewaretoken': '{{ csrf_token }}'
      },
      success: addMorePostAjax,
      dataType: 'html',
      error: function(request, status, error){
        alert('오류발생');
        // alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
      },
    });
  }

  function addMorePostAjax(data, textStatus, jqXHR) {
    $('#post_list_ajax').append(data);
  }
</script>