config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('post:post_list'), name='root'),
]

# NOTE: serving media files uploaded by a user during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# NOTE: debug_toolbar용 url 설정
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('<username>/list', my_post_list, name='my_post_list'),
    path('<username>/list/detail', my_post_list_detail, name='my_post_list_detail'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('follow', follow_post_list, name='follow_post_list'),
    path('like', post_like, name='post_like'),
    path('comment/new', comment_new, name='comment_new'),
    path('comment/delete', comment_delete, name='comment_delete'),
    path('comment/more', comment_more, name='comment_more'),
    path('explore/tags/<tag>/', post_list, name='post_search'),

    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^new/$', views.post_new, name='post_new'),



    # url(r'^explore/tags/(?P<tag>\w+)/$', views.post_list, name='post_search'),

    # url(r'^(?P<username>\w+)/list/$', views.my_post_list, name='my_post_list'),
    # url(r'^(?P<username>\w+)/list/detail/$', views.my_post_list_detail, name='my_post_list_detail'),
    # url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    # url(r'^comment/new/$', views.comment_new, name='comment_new'),
    # url(r'^comment/delete/$', views.comment_delete, name='comment_delete'),
    # url(r'^comment/more/$', views.comment_more, name='comment_more'),
    # url(r'^like/$', views.post_like, name='post_like'),
    # url(r'^follow/$', views.follow_post_list, name='follow_post_list'),
    # url(r'^(?P<username>\w+)/list/follow/$', views.follow_list, name='follow__list'),
]

config/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
  <title>{% block title %}Instagram{% endblock %}</title>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

  <!-- favicon -->
  <link rel="icon" sizes="192x192" href="{% static 'images/icon/icon_192x192.png' %}">
  <link rel="apple-touch-icon-precomposed" sizes="180x180"  href="{% static 'images/icon/icon_180x180.png' %}">

  <!-- 부트스트랩 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/layout.css' %}">
  <link rel="stylesheet" href="{% static 'css/post.css' %}">
  <link rel="stylesheet" href="{% static 'css/mylist.css' %}">
  <link rel="stylesheet" href="{% static 'css/search.css' %}">
  <link rel="stylesheet" href="{% static 'css/account_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/post_upload.css' %}">
  <link rel="stylesheet" href="{% static 'css/media.css' %}">

  <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
  <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container-fluid">
    <nav class="navbar navbar-default">
      <div class="nav-wrap">
        <a class="logo pull-left" href="/"></a>
        <form class="search-form" action="{% url "post:post_list" %}" method="post">
          {% csrf_token %}
          <input class="tag-search" type="text" name="tag" placeholder="검색" pattern="#?[\wㄱ-ㅎ|ㅏ-ㅣ|가-힣]+" title="특수문자, 공백 입력불가" required >
          {# <input type="submit"> - input이 하나일 때는 별도의 submit 없이 엔터로 전송이 가능하다.#}
          <span class="search-icon"></span>
        </form>
        <span class="pull-right">
          <a class="new-post" href="{% url "post:post_new" %}"></a>
          <a class="follow-list" href="{% url "post:follow_post_list" %}"></a>
          {% if user.is_authenticated %}
          <a class="account" href="{% url "post:my_post_list" user.username %}"></a>
          {% else %}
          <a  class="account" href="{% url "account_login" %}"></a>
          {% endif %}
        </span>

      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </div>
  {% if messages %}
  <script type="text/javascript">
  {% for message in messages %}
  alert("{{ message.message }}");
  {% endfor %}
  </script>
  {% endif %}

  <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>